concurrent = 4
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Docker Runner"
  url = "http://gitlab:8000"
  id = 1
  token = "glrtr-GgSJsyveRehyzxQhWhu-"
  token_obtained_at = 2025-10-04T18:45:46Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"

  # Add this to create a network for each job
  environment = ["FF_NETWORK_PER_BUILD=1"]
  
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0
    network_mode = "env_gitlab-network"  # Use your compose network's full name
    
     # This is crucial: Map 'gitlab' to the host's IP for job containers
    extra_hosts = ["gitlab:host-gateway"]
