spring:
  application:
    name: config-management-portal

info:
  app:
    name: "config-management-portal"
    version: ${SERVICE_VERSION:N/A}
    enablecache: true

server:
  host: ${HOST_IP}
  port: ${EXPOSED_PORT:8080}
  error:
    whitelabel:
      enabled: true
  servlet:
    context-path: /
  tomcat:
    connection-timeout: 10000
  shutdown: graceful
  forward-headers-strategy: native

configservice:
  management:
    client:
      configservice:
        url: "http://localhost:8081"
